service: serverless-data-pipeline

provider:
  name: aws
  region: eu-central-1
  runtime: python3.7
  stage: ${opt:stage}
  # add your own lambda role ARN here
  role: <YOUR_LAMBDA_ROLE_ARN_MUST_COME_HERE>

plugins:
  - serverless-s3-remover

custom:
  bucket: ${self:service}-${self:provider.stage}
  bucket_glue_scripts: ${self:custom.bucket}-glue-scripts
  glue_crawler: load-${self:provider.stage}
  glue_job: unzip-${self:provider.stage}
  glue_job_script_location: s3://${self:custom.bucket_glue_scripts}/unzip.py
  # add your own glue role ARN here
  glue_role: <YOUR_GLUE_ROLE_ARN_MUST_COME_HERE>
  athena_db: ${self:custom.bucket}
  remover:
    buckets:
      - ${self:custom.bucket}
      - ${self:custom.bucket_glue_scripts}

functions:
  unzip:
    handler: lambda/unzip.handler
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: raw/
            - suffix: .zip
    environment:
        DEST_BUCKET: ${self:custom.bucket}
        DEST_KEY: unzip/
        GLUE_JOB: ${self:custom.glue_job}

  extract:
    handler: lambda/extract.handler
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: unzip/
            - suffix: .eml
    environment:
        DEST_BUCKET: ${self:custom.bucket}
        DEST_KEY: extract/

  load:
    handler: lambda/load.handler
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: extract/
            - suffix: .json
    environment:
      GLUE_CRAWLER: ${self:custom.glue_crawler}

resources:
  Resources:
    GlueJob:
      Type: AWS::Glue::Job
      Properties: 
        Role: ${self:custom.glue_role}
        Command:   
          Name: pythonshell  
          ScriptLocation: ${self:custom.glue_job_script_location}
        Name: unzip-${self:provider.stage}

    S3GlueScripts:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket_glue_scripts}

    GlueCrawler:
      Type: AWS::Glue::Crawler
      Properties:
        DatabaseName: ${self:custom.athena_db}
        Name: ${self:custom.glue_crawler}
        Role: ${self:custom.glue_role}
        TablePrefix: messages_
        Targets:
          S3Targets:
            -  Path: s3://${self:custom.bucket}/extract/